### PR TITLE
Fix parcelable deprecation

### LINKED ISSUE #1138: filepicker/FilePickerDelegate.java uses or overrides a deprecated API.
**Describe the bug**
`flutter build appbundle`
produces the following message:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/user1/.pub-cache/hosted/pub.dartlang.org/file_picker-5.2.0+1/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
5.2.0+1

**Flutter Version details**
<details>
<summary>
$ flutter doctor -v
</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on Linux Mint 20.3 5.4.0-126-generic, locale en_US.UTF-8)
    • Flutter version 3.3.2 on channel stable at /home/user1/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/user1/Android
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/user1/Android
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 64.1.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20.3 5.4.0-126-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.79

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by navaronbracke**
Fixes #1138

@miguelpruivo I could not test the change on an emulator due to a conflict with the NDK (I have a newer version installed than what the example app wants). Could you look into that?

### CODE REVIEW

File: android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java [hunk 1]
```diff
@@ -208,6 +209,15 @@ private static void finishWithAlreadyActiveError(final MethodChannel.Result resu
         result.error("already_active", "File picker is already active", null);
     }
 
+    @SuppressWarnings("deprecation")
+    private ArrayList<Parcelable> getSelectedItems(Bundle bundle){
+        if(Build.VERSION.SDK_INT >= 33){
```
Comment (navaronbracke) [inline android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java:214]: I saw that there was a similar issue with using the Tiramisu constant. Shouldn't we encourage people to update to the latest compile SDK version? (and fix the two usages of `33` in the codebase)

**Review by miguelpruivo — APPROVED** [review]
