### PR TITLE
Fix Issue 1505(Fix cache delete)

### LINKED ISSUE #1505: Not work `clearTemporaryFiles()`  on Android
**Describe the bug**
Not work `clearTemporaryFiles()`  on Android

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android14

**How are you picking?**
None.

**Details to reproduce the issue**
None.

**Error Log**
None.

**Screenshots and/or video**
None.

**Flutter Version details**
```
[✓] Flutter (Channel stable, 3.19.5, on macOS 13.6 22G120 darwin-arm64, locale ja-JP)
    • Flutter version 3.19.5 on channel stable at /Users/stakano/fvm/versions/3.19.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
```

**Additional context**

Maybe this PR has an influence
https://github.com/miguelpruivo/flutter_file_picker/pull/1466/files

Because, Java File.delete cannot delete unless the folder is empty.

### PR DESCRIPTION
**Pull request by stakanojmdc**
Fix #1505 

implement recursive delete file.
because, Java cannot delete not-empty directory.

### CODE REVIEW

File: android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java [hunk 1]
```diff
@@ -471,4 +465,18 @@ private static String getDocumentPathFromTreeUri(final Uri treeUri) {
         else return File.separator;
     }
 
+    private static void recursiveDeleteFile(final File file) throws Exception {
+        if (!file.exists()) {
```
Comment (navaronbracke) [inline android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:469]: The old code had a null check on the file too. Perhaps add that here as well?

**Review by navaronbracke — CHANGES_REQUESTED** [review]

**Comment by navaronbracke** [comment]
The version & changelog also needs to be updated.

File: android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java (hunk 1 above)
Comment (stakanojmdc) [reply android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java]: Thanks, I fixed. https://github.com/miguelpruivo/flutter_file_picker/pull/1507/commits/375a10a6d28bb487f2dcae088b7ecf48d3f7852e

**Review by navaronbracke — APPROVED** [review]
